from dataclasses import dataclass
from enum import Enum
from phoenix6.configs import CurrentLimitsConfigs


@dataclass
class RobotEnergyProfile:
    intake: CurrentLimitsConfigs
    serializer: CurrentLimitsConfigs
    indexer1: CurrentLimitsConfigs
    indexer2: CurrentLimitsConfigs
    shooter: CurrentLimitsConfigs
    drivetrain: CurrentLimitsConfigs


class EnergyProfiles(Enum):
    DEFAULT = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(100)
        .with_supply_current_limit(55)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(120)
        .with_supply_current_limit(70)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(60)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(80)
        .with_supply_current_limit(50)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(80)
        .with_supply_current_limit(50)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    FAR_FIELD_PASS = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(30)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(70)
        .with_supply_current_limit(20)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(110)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(100)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(70)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    MID_FIELD_PASS = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(60)
        .with_supply_current_limit(30)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(100)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(100)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(70)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    SHOOT = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(30)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(20)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(120)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(50)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(120)
        .with_supply_current_limit(80)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(120)
        .with_supply_current_limit(70)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    OVERCLOCK = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(150)
        .with_supply_current_limit(90)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    BROWNOUT = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
    AUTO_DRIVE = RobotEnergyProfile(
        drivetrain=CurrentLimitsConfigs()
        .with_stator_current_limit(140)
        .with_supply_current_limit(100)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        intake=CurrentLimitsConfigs()
        .with_stator_current_limit(140)
        .with_supply_current_limit(50)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        shooter=CurrentLimitsConfigs()
        .with_stator_current_limit(120)
        .with_supply_current_limit(60)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        serializer=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer1=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
        indexer2=CurrentLimitsConfigs()
        .with_stator_current_limit(40)
        .with_supply_current_limit(40)
        .with_supply_current_limit_enable(True)
        .with_stator_current_limit_enable(True),
    )
